import { postFetch } from '../../../Utils/Fetch';

export const addNutrition = async (user, date,
  foodNameB,
  caloriesB,
  saturatedB,
  transB,
  polyunsaturatedB,
  monosaturatedB,
  cholesterolB,
  sodiumB,
  carbsB,
  fiberB,
  sugarsB,
  proteinB,
  vitaminAB,
  vitaminCB,
  vitaminDB,
  calciumB,
  ironB,
  potassiumB,
  foodNameL,
  caloriesL,
  saturatedL,
  transL,
  polyunsaturatedL,
  monosaturatedL,
  cholesterolL,
  sodiumL,
  carbsL,
  fiberL,
  sugarsL,
  proteinL,
  vitaminAL,
  vitaminCL,
  vitaminDL,
  calciumL,
  ironL,
  potassiumL,
  foodNameD,
  caloriesD,
  saturatedD,
  transD,
  polyunsaturatedD,
  monosaturatedD,
  cholesterolD,
  sodiumD,
  carbsD,
  fiberD,
  sugarsD,
  proteinD,
  vitaminAD,
  vitaminCD,
  vitaminDD,
  calciumD,
  ironD,
  potassiumD,
  foodNameBB,
  caloriesBB,
  saturatedBB,
  transBB,
  polyunsaturatedBB,
  monosaturatedBB,
  cholesterolBB,
  sodiumBB,
  carbsBB,
  fiberBB,
  sugarsBB,
  proteinBB,
  vitaminABB,
  vitaminCBB,
  vitaminDBB,
  calciumBB,
  ironBB,
  potassiumBB,
  foodNameBed,
  caloriesBed,
  saturatedBed,
  transBed,
  polyunsaturatedBed,
  monosaturatedBed,
  cholesterolBed,
  sodiumBed,
  carbsBed,
  fiberBed,
  sugarsBed,
  proteinBed,
  vitaminABed,
  vitaminCBed,
  vitaminDBed,
  calciumBed,
  ironBed,
  potassiumBed) => {
  await postFetch(`/bgtracker/nutritions/add/${user.id}`, {
    user_id: user.id,
    date: date,
    foodNameB: foodNameB,
    caloriesB: caloriesB,
    saturatedB: saturatedB,
    transB: transB,
    polyunsaturatedB: polyunsaturatedB,
    monosaturatedB: monosaturatedB,
    cholesterolB: cholesterolB,
    sodiumB: sodiumB,
    carbsB: carbsB,
    fiberB: fiberB,
    sugarsB: sugarsB,
    proteinB: proteinB,
    vitaminAB: vitaminAB,
    vitaminCB: vitaminCB,
    vitaminDB: vitaminDB,
    calciumB: calciumB,
    ironB: ironB,
    potassiumB: potassiumB,
    foodNameL: foodNameL,
    caloriesL: caloriesL,
    saturatedL: saturatedL,
    transL: transL,
    polyunsaturatedL: polyunsaturatedL,
    monosaturatedL: monosaturatedL,
    cholesterolL: cholesterolL,
    sodiumL: sodiumL,
    carbsL: carbsL,
    fiberL: fiberL,
    sugarsL: sugarsL,
    proteinL: proteinL,
    vitaminAL: vitaminAL,
    vitaminCL: vitaminCL,
    vitaminDL: vitaminDL,
    calciumL: calciumL,
    ironL: ironL,
    potassiumL: potassiumL,
    foodNameD: foodNameD,
    caloriesD: caloriesD,
    saturatedD: saturatedD,
    transD: transD,
    polyunsaturatedD: polyunsaturatedD,
    monosaturatedD: monosaturatedD,
    cholesterolD: cholesterolD,
    sodiumD: sodiumD,
    carbsD: carbsD,
    fiberD: fiberD,
    sugarsD: sugarsD,
    proteinD: proteinD,
    vitaminAD: vitaminAD,
    vitaminCD: vitaminCD,
    vitaminDD: vitaminDD,
    calciumD: calciumD,
    ironD: ironD,
    potassiumD: potassiumD,
    foodNameBB: foodNameBB,
    caloriesBB: caloriesBB,
    saturatedBB: saturatedBB,
    transBB: transBB,
    polyunsaturatedBB: polyunsaturatedBB,
    monosaturatedBB: monosaturatedBB,
    cholesterolBB: cholesterolBB,
    sodiumBB: sodiumBB,
    carbsBB: carbsBB,
    fiberBB: fiberBB,
    sugarsBB: sugarsBB,
    proteinBB: proteinBB,
    vitaminABB: vitaminABB,
    vitaminCBB: vitaminCBB,
    vitaminDBB: vitaminDBB,
    calciumBB: calciumBB,
    ironBB: ironBB,
    potassiumBB: potassiumBB,
    foodNameBed: foodNameBed,
    caloriesBed: caloriesBed,
    saturatedBed: saturatedBed,
    transBed: transBed,
    polyunsaturatedBed: polyunsaturatedBed,
    monosaturatedBed: monosaturatedBed,
    cholesterolBed: cholesterolBed,
    sodiumBed: sodiumBed,
    carbsBed: carbsBed,
    fiberBed: fiberBed,
    sugarsBed: sugarsBed,
    proteinBed: proteinBed,
    vitaminABed: vitaminABed,
    vitaminCBed: vitaminCBed,
    vitaminDBed: vitaminDBed,
    calciumBed: calciumBed,
    ironBed: ironBed,
    potassiumBed: potassiumBed,
  }).catch((err) => console.log(err));
}

export const deleteNutrition = async (user, nutritions, editIdx) => {
  await postFetch(`/bgtracker/nutritions/delete/${user.id}`, {
    id: nutritions[editIdx + 1].id,
  }).catch((err) => console.log(err));
};

export const editNutrition = async (user, nutritions, editIdx) => {
  await postFetch(`/bgtracker/nutritions/edit/${user.id}`, {
    id: nutritions[editIdx].id,
    user_id: user.id,
    date: nutritions[editIdx].date,
    foodNameB: nutritions[editIdx].foodNameB,
    caloriesB: nutritions[editIdx].caloriesB,
    saturatedB: nutritions[editIdx].saturatedB,
    transB: nutritions[editIdx].transB,
    polyunsaturatedB: nutritions[editIdx].polyunsaturatedB,
    monosaturatedB: nutritions[editIdx].monosaturatedB,
    cholesterolB: nutritions[editIdx].cholesterolB,
    sodiumB: nutritions[editIdx].sodiumB,
    carbsB: nutritions[editIdx].carbsB,
    fiberB: nutritions[editIdx].fiberB,
    sugarsB: nutritions[editIdx].sugarsB,
    proteinB: nutritions[editIdx].proteinB,
    vitaminAB: nutritions[editIdx].vitaminAB,
    vitaminCB: nutritions[editIdx].vitaminCB,
    vitaminDB: nutritions[editIdx].vitaminDB,
    calciumB: nutritions[editIdx].calciumB,
    ironB: nutritions[editIdx].ironB,
    potassiumB: nutritions[editIdx].potassiumB,
    foodNameL: nutritions[editIdx].foodNameL,
    caloriesL: nutritions[editIdx].caloriesL,
    saturatedL: nutritions[editIdx].saturatedL,
    transL: nutritions[editIdx].transL,
    polyunsaturatedL: nutritions[editIdx].polyunsaturatedL,
    monosaturatedL: nutritions[editIdx].monosaturatedL,
    cholesterolL: nutritions[editIdx].cholesterolL,
    sodiumL: nutritions[editIdx].sodiumL,
    carbsL: nutritions[editIdx].carbsL,
    fiberL: nutritions[editIdx].fiberL,
    sugarsL: nutritions[editIdx].sugarsL,
    proteinL: nutritions[editIdx].proteinL,
    vitaminAL: nutritions[editIdx].vitaminAL,
    vitaminCL: nutritions[editIdx].vitaminCL,
    vitaminDL: nutritions[editIdx].vitaminDL,
    calciumL: nutritions[editIdx].calciumL,
    ironL: nutritions[editIdx].ironL,
    potassiumL: nutritions[editIdx].potassiumL,
    foodNameD: nutritions[editIdx].foodNameD,
    caloriesD: nutritions[editIdx].caloriesD,
    saturatedD: nutritions[editIdx].saturatedD,
    transD: nutritions[editIdx].transD,
    polyunsaturatedD: nutritions[editIdx].polyunsaturatedD,
    monosaturatedD: nutritions[editIdx].monosaturatedD,
    cholesterolD: nutritions[editIdx].cholesterolD,
    sodiumD: nutritions[editIdx].sodiumD,
    carbsD: nutritions[editIdx].carbsD,
    fiberD: nutritions[editIdx].fiberD,
    sugarsD: nutritions[editIdx].sugarsD,
    proteinD: nutritions[editIdx].proteinD,
    vitaminAD: nutritions[editIdx].vitaminAD,
    vitaminCD: nutritions[editIdx].vitaminCD,
    vitaminDD: nutritions[editIdx].vitaminDD,
    calciumD: nutritions[editIdx].calciumD,
    ironD: nutritions[editIdx].ironD,
    potassiumD: nutritions[editIdx].potassiumD,
    foodNameBB: nutritions[editIdx].foodNameBB,
    caloriesBB: nutritions[editIdx].caloriesBB,
    saturatedBB: nutritions[editIdx].saturatedBB,
    transBB: nutritions[editIdx].transBB,
    polyunsaturatedBB: nutritions[editIdx].polyunsaturatedBB,
    monosaturatedBB: nutritions[editIdx].monosaturatedBB,
    cholesterolBB: nutritions[editIdx].cholesterolBB,
    sodiumBB: nutritions[editIdx].sodiumBB,
    carbsBB: nutritions[editIdx].carbsBB,
    fiberBB: nutritions[editIdx].fiberBB,
    sugarsBB: nutritions[editIdx].sugarsBB,
    proteinBB: nutritions[editIdx].proteinBB,
    vitaminABB: nutritions[editIdx].vitaminABB,
    vitaminCBB: nutritions[editIdx].vitaminCBB,
    vitaminDBB: nutritions[editIdx].vitaminDBB,
    calciumBB: nutritions[editIdx].calciumBB,
    ironBB: nutritions[editIdx].ironBB,
    potassiumBB: nutritions[editIdx].potassiumBB,
    foodNameBed: nutritions[editIdx].foodNameBed,
    caloriesBed: nutritions[editIdx].caloriesBed,
    saturatedBed: nutritions[editIdx].saturatedBed,
    transBed: nutritions[editIdx].transBed,
    polyunsaturatedBed: nutritions[editIdx].polyunsaturatedBed,
    monosaturatedBed: nutritions[editIdx].monosaturatedBed,
    cholesterolBed: nutritions[editIdx].cholesterolBed,
    sodiumBed: nutritions[editIdx].sodiumBed,
    carbsBed: nutritions[editIdx].carbsBed,
    fiberBed: nutritions[editIdx].fiberBed,
    sugarsBed: nutritions[editIdx].sugarsBed,
    proteinBed: nutritions[editIdx].proteinBed,
    vitaminABed: nutritions[editIdx].vitaminABed,
    vitaminCBed: nutritions[editIdx].vitaminCBed,
    vitaminDBed: nutritions[editIdx].vitaminDBed,
    calciumBed: nutritions[editIdx].calciumBed,
    ironBed: nutritions[editIdx].ironBed,
    potassiumBed: nutritions[editIdx].potassiumBed,
  }).catch((err) => console.log(err))
};

export const removeNutrition = (i, nutritions) => {
  const arr = nutritions;
  arr.splice(i, 1);
  nutritions = arr;
};
