const express = require('express');
const router = express.Router();
const { bgtracker } = require('../../../db/db');
const { updateNutrition } = require('../../../db/sql/bgtracker/nutritions');

router.post('/:user_id', (req, res) => {
  const {
    id = req.body.id,
    user_id = req.params.user_id,
    date = req.body.date,
    foodNameB = req.body.foodNameB,
    caloriesB = req.body.caloriesB,
    saturatedB = req.body.saturatedB,
    transB = req.body.transB,
    polyunsaturatedB = req.body.polyunsaturatedB,
    monosaturatedB = req.body.monosaturatedB,
    cholesterolB = req.body.cholesterolB,
    sodiumB = req.body.sodiumB,
    carbsB = req.body.carbsB,
    fiberB = req.body.fiberB,
    sugarsB = req.body.sugarsB,
    proteinB = req.body.proteinB,
    vitaminAB = req.body.vitaminAB,
    vitaminCB = req.body.vitaminCB,
    vitaminDB = req.body.vitaminDB,
    calciumB = req.body.calciumB,
    ironB = req.body.ironB,
    potassiumB = req.body.potassiumB,
    foodNameL = req.body.foodNameL,
    caloriesL = req.body.caloriesL,
    saturatedL = req.body.saturatedL,
    transL = req.body.transL,
    polyunsaturatedL = req.body.polyunsaturatedL,
    monosaturatedL = req.body.monosaturatedL,
    cholesterolL = req.body.cholesterolL,
    sodiumL = req.body.sodiumL,
    carbsL = req.body.carbsL,
    fiberL = req.body.fiberL,
    sugarsL = req.body.sugarsL,
    proteinL = req.body.proteinL,
    vitaminAL = req.body.vitaminAL,
    vitaminCL = req.body.vitaminCL,
    vitaminDL = req.body.vitaminDL,
    calciumL = req.body.calciumL,
    ironL = req.body.ironL,
    potassiumL = req.body.potassiumL,
    foodNameD = req.body.foodNameD,
    caloriesD = req.body.caloriesD,
    saturatedD = req.body.saturatedD,
    transD = req.body.transD,
    polyunsaturatedD = req.body.polyunsaturatedD,
    monosaturatedD = req.body.monosaturatedD,
    cholesterolD = req.body.cholesterolD,
    sodiumD = req.body.sodiumD,
    carbsD = req.body.carbsD,
    fiberD = req.body.fiberD,
    sugarsD = req.body.sugarsD,
    proteinD = req.body.proteinD,
    vitaminAD = req.body.vitaminAD,
    vitaminCD = req.body.vitaminCD,
    vitaminDD = req.body.vitaminDD,
    calciumD = req.body.calciumD,
    ironD = req.body.ironD,
    potassiumD = req.body.potassiumD,
    foodNameBB = req.body.foodNameBB,
    caloriesBB = req.body.caloriesBB,
    saturatedBB = req.body.saturatedBB,
    transBB = req.body.transBB,
    polyunsaturatedBB = req.body.polyunsaturatedBB,
    monosaturatedBB = req.body.monosaturatedBB,
    cholesterolBB = req.body.cholesterolBB,
    sodiumBB = req.body.sodiumBB,
    carbsBB = req.body.carbsBB,
    fiberBB = req.body.fiberBB,
    sugarsBB = req.body.sugarsBB,
    proteinBB = req.body.proteinBB,
    vitaminABB = req.body.vitaminABB,
    vitaminCBB = req.body.vitaminCBB,
    vitaminDBB = req.body.vitaminDBB,
    calciumBB = req.body.calciumBB,
    ironBB = req.body.ironBB,
    potassiumBB = req.body.potassiumBB,
    foodNameBed = req.body.foodNameBed,
    saturatedBed = req.body.saturatedBed,
    caloriesBed = req.body.caloriesBed,
    transBed = req.body.transBed,
    polyunsaturatedBed = req.body.polyunsaturatedBed,
    monosaturatedBed = req.body.monosaturatedBed,
    cholesterolBed = req.body.cholesterolBed,
    sodiumBed = req.body.sodiumBed,
    carbsBed = req.body.carbsBed,
    fiberBed = req.body.fiberBed,
    sugarsBed = req.body.sugarsBed,
    proteinBed = req.body.proteinBed,
    vitaminABed = req.body.vitaminABed,
    vitaminCBed = req.body.vitaminCBed,
    vitaminDBed = req.body.vitaminDBed,
    calciumBed = req.body.calciumBed,
    ironBed = req.body.ironBed,
    potassiumBed = req.body.potassiumBed,
  } = req.query;
  bgtracker.query(
    updateNutrition,
    [
      id,
      user_id,
      date,
      foodNameB,
      caloriesB,
      saturatedB,
      transB,
      polyunsaturatedB,
      monosaturatedB,
      cholesterolB,
      sodiumB,
      carbsB,
      fiberB,
      sugarsB,
      proteinB,
      vitaminAB,
      vitaminCB,
      vitaminDB,
      calciumB,
      ironB,
      potassiumB,
      foodNameL,
      caloriesL,
      saturatedL,
      transL,
      polyunsaturatedL,
      monosaturatedL,
      cholesterolL,
      sodiumL,
      carbsL,
      fiberL,
      sugarsL,
      proteinL,
      vitaminAL,
      vitaminCL,
      vitaminDL,
      calciumL,
      ironL,
      potassiumL,
      foodNameD,
      caloriesD,
      saturatedD,
      transD,
      polyunsaturatedD,
      monosaturatedD,
      cholesterolD,
      sodiumD,
      carbsD,
      fiberD,
      sugarsD,
      proteinD,
      vitaminAD,
      vitaminCD,
      vitaminDD,
      calciumD,
      ironD,
      potassiumD,
      foodNameBB,
      caloriesBB,
      saturatedBB,
      transBB,
      polyunsaturatedBB,
      monosaturatedBB,
      cholesterolBB,
      sodiumBB,
      carbsBB,
      fiberBB,
      sugarsBB,
      proteinBB,
      vitaminABB,
      vitaminCBB,
      vitaminDBB,
      calciumBB,
      ironBB,
      potassiumBB,
      foodNameBed,
      caloriesBed,
      saturatedBed,
      transBed,
      polyunsaturatedBed,
      monosaturatedBed,
      cholesterolBed,
      sodiumBed,
      carbsBed,
      fiberBed,
      sugarsBed,
      proteinBed,
      vitaminABed,
      vitaminCBed,
      vitaminDBed,
      calciumBed,
      ironBed,
      potassiumBed,
    ],
    (err, results, rows) => {
      if (err) {
        return res.send(err.message);
      } else {
        res.send('Successfully Edited Row');
      }
    }
  );
});

module.exports = router;
