const copyNutritionsTable =
  `CREATE TEMPORARY TABLE tmpnutritions(
    user_id int not null,
    date text not null,
    foodNameB text not null,
    caloriesB int not null,
    saturatedB decimal(10,3) not null,
    transB decimal(10,3) not null,
    polyunsaturatedB decimal(10,3) not null,
    monosaturatedB decimal(10,3) not null,
    cholesterolB int not null,
    sodiumB int not null,
    carbsB int not null,
    fiberB int not null,
    sugarsB decimal(10,3) not null,
    proteinB decimal(10,3) not null,
    vitaminAB int not null,
    vitaminCB int not null,
    vitaminDB int not null,
    calciumB int not null,
    ironB decimal(10,3) not null,
    potassiumB int not null,
    foodNameL text not null,
    caloriesL int not null,
    saturatedL decimal(10,3) not null,
    transL decimal(10,3) not null,
    polyunsaturatedL decimal(10,3) not null,
    monosaturatedL decimal(10,3) not null,
    cholesterolL int not null,
    sodiumL int not null,
    carbsL int not null,
    fiberL int not null,
    sugarsL decimal(10,3) not null,
    proteinL decimal(10,3) not null,
    vitaminAL int not null,
    vitaminCL int not null,
    vitaminDL int not null,
    calciumL int not null,
    ironL decimal(10,3) not null,
    potassiumL int not null,
    foodNameD text not null,
    caloriesD int not null,
    saturatedD decimal(10,3) not null,
    transD decimal(10,3) not null,
    polyunsaturatedD decimal(10,3) not null,
    monosaturatedD decimal(10,3) not null,
    cholesterolD int not null,
    sodiumD int not null,
    carbsD int not null,
    fiberD int not null,
    sugarsD decimal(10,3) not null,
    proteinD decimal(10,3) not null,
    vitaminAD int not null,
    vitaminCD int not null,
    vitaminDD int not null,
    calciumD int not null,
    ironD decimal(10,3) not null,
    potassiumD int not null,
    foodNameBB text not null,
    caloriesBB int not null,
    saturatedBB decimal(10,3) not null,
    transBB decimal(10,3) not null,
    polyunsaturatedBB decimal(10,3) not null,
    monosaturatedBB decimal(10,3) not null,
    cholesterolBB int not null,
    sodiumBB int not null,
    carbsBB int not null,
    fiberBB int not null,
    sugarsBB decimal(10,3) not null,
    proteinBB decimal(10,3) not null,
    vitaminABB int not null,
    vitaminCBB int not null,
    vitaminDBB int not null,
    calciumBB int not null,
    ironBB decimal(10,3) not null,
    potassiumBB int not null,
    foodNameBed text not null,
    caloriesBed int not null,
    saturatedBed decimal(10,3) not null,
    transBed decimal(10,3) not null,
    polyunsaturatedBed decimal(10,3) not null,
    monosaturatedBed decimal(10,3) not null,
    cholesterolBed int not null,
    sodiumBed int not null,
    carbsBed int not null,
    fiberBed int not null,
    sugarsBed decimal(10,3) not null,
    proteinBed decimal(10,3) not null,
    vitaminABed int not null,
    vitaminCBed int not null,
    vitaminDBed int not null,
    calciumBed int not null,
    ironBed decimal(10,3) not null,
    potassiumBed int not null);\
    INSERT INTO tmpnutritions(user_id,date,foodNameB,caloriesB,saturatedB,
      transB,polyunsaturatedB,monosaturatedB,cholesterolB,sodiumB,carbsB,
      fiberB,sugarsB,proteinB,vitaminAB,vitaminCB,vitaminDB,calciumB,
      ironB,potassiumB,foodNameL,caloriesL,saturatedL,transL,
      polyunsaturatedL,monosaturatedL,cholesterolL,sodiumL,carbsL,fiberL,
      sugarsL,proteinL,vitaminAL,vitaminCL,vitaminDL,calciumL,ironL,
      potassiumL,foodNameD,caloriesD,saturatedD,transD,polyunsaturatedD,
      monosaturatedD,cholesterolD,sodiumD,carbsD,fiberD,sugarsD,proteinD,
      vitaminAD,vitaminCD,vitaminDD,calciumD,ironD,potassiumD,foodNameBB,
      caloriesBB,saturatedBB,transBB,polyunsaturatedBB,monosaturatedBB,
      cholesterolBB,sodiumBB,carbsBB,fiberBB,sugarsBB,proteinBB,vitaminABB,
      vitaminCBB,vitaminDBB,calciumBB,ironBB,potassiumBB,foodNameBed,
      caloriesBed,saturatedBed,transBed,polyunsaturatedBed,monosaturatedBed,
      cholesterolBed,sodiumBed,carbsBed,fiberBed,sugarsBed,proteinBed,
      vitaminABed,vitaminCBed,vitaminDBed,calciumBed,ironBed,potassiumBed)
      SELECT user_id,date,foodNameB,caloriesB,saturatedB,
      transB,polyunsaturatedB,monosaturatedB,cholesterolB,sodiumB,carbsB,
      fiberB,sugarsB,proteinB,vitaminAB,vitaminCB,vitaminDB,calciumB,
      ironB,potassiumB,foodNameL,caloriesL,saturatedL,transL,
      polyunsaturatedL,monosaturatedL,cholesterolL,sodiumL,carbsL,fiberL,
      sugarsL,proteinL,vitaminAL,vitaminCL,vitaminDL,calciumL,ironL,
      potassiumL,foodNameD,caloriesD,saturatedD,transD,polyunsaturatedD,
      monosaturatedD,cholesterolD,sodiumD,carbsD,fiberD,sugarsD,proteinD,
      vitaminAD,vitaminCD,vitaminDD,calciumD,ironD,potassiumD,foodNameBB,
      caloriesBB,saturatedBB,transBB,polyunsaturatedBB,monosaturatedBB,
      cholesterolBB,sodiumBB,carbsBB,fiberBB,sugarsBB,proteinBB,vitaminABB,
      vitaminCBB,vitaminDBB,calciumBB,ironBB,potassiumBB,foodNameBed,
      caloriesBed,saturatedBed,transBed,polyunsaturatedBed,monosaturatedBed,
      cholesterolBed,sodiumBed,carbsBed,fiberBed,sugarsBed,proteinBed,
      vitaminABed,vitaminCBed,vitaminDBed,calciumBed,ironBed,potassiumBed
       FROM nutritions;
    DROP TABLE nutritions;\
  CREATE TABLE nutritions(
    id int not null auto_increment,
    user_id int not null,
    date text not null,
    foodNameB text not null,
    caloriesB int not null,
    saturatedB decimal(10,3) not null,
    transB decimal(10,3) not null,
    polyunsaturatedB decimal(10,3) not null,
    monosaturatedB decimal(10,3) not null,
    cholesterolB int not null,
    sodiumB int not null,
    carbsB int not null,
    fiberB int not null,
    sugarsB decimal(10,3) not null,
    proteinB decimal(10,3) not null,
    vitaminAB int not null,
    vitaminCB int not null,
    vitaminDB int not null,
    calciumB int not null,
    ironB decimal(10,3) not null,
    potassiumB int not null,
    foodNameL text not null,
    caloriesL int not null,
    saturatedL decimal(10,3) not null,
    transL decimal(10,3) not null,
    polyunsaturatedL decimal(10,3) not null,
    monosaturatedL decimal(10,3) not null,
    cholesterolL int not null,
    sodiumL int not null,
    carbsL int not null,
    fiberL int not null,
    sugarsL decimal(10,3) not null,
    proteinL decimal(10,3) not null,
    vitaminAL int not null,
    vitaminCL int not null,
    vitaminDL int not null,
    calciumL int not null,
    ironL decimal(10,3) not null,
    potassiumL int not null,
    foodNameD text not null,
    caloriesD int not null,
    saturatedD decimal(10,3) not null,
    transD decimal(10,3) not null,
    polyunsaturatedD decimal(10,3) not null,
    monosaturatedD decimal(10,3) not null,
    cholesterolD int not null,
    sodiumD int not null,
    carbsD int not null,
    fiberD int not null,
    sugarsD decimal(10,3) not null,
    proteinD decimal(10,3) not null,
    vitaminAD int not null,
    vitaminCD int not null,
    vitaminDD int not null,
    calciumD int not null,
    ironD decimal(10,3) not null,
    potassiumD int not null,
    foodNameBB text not null,
    caloriesBB int not null,
    saturatedBB decimal(10,3) not null,
    transBB decimal(10,3) not null,
    polyunsaturatedBB decimal(10,3) not null,
    monosaturatedBB decimal(10,3) not null,
    cholesterolBB int not null,
    sodiumBB int not null,
    carbsBB int not null,
    fiberBB int not null,
    sugarsBB decimal(10,3) not null,
    proteinBB decimal(10,3) not null,
    vitaminABB int not null,
    vitaminCBB int not null,
    vitaminDBB int not null,
    calciumBB int not null,
    ironBB decimal(10,3) not null,
    potassiumBB int not null,
    foodNameBed text not null,
    caloriesBed int not null,
    saturatedBed decimal(10,3) not null,
    transBed decimal(10,3) not null,
    polyunsaturatedBed decimal(10,3) not null,
    monosaturatedBed decimal(10,3) not null,
    cholesterolBed int not null,
    sodiumBed int not null,
    carbsBed int not null,
    fiberBed int not null,
    sugarsBed decimal(10,3) not null,
    proteinBed decimal(10,3) not null,
    vitaminABed int not null,
    vitaminCBed int not null,
    vitaminDBed int not null,
    calciumBed int not null,
    ironBed decimal(10,3) not null,
    potassiumBed int not null,
    primary key (id));\
  INSERT INTO nutritions(user_id,date,foodNameB,caloriesB,saturatedB,
    transB,polyunsaturatedB,monosaturatedB,cholesterolB,sodiumB,carbsB,
    fiberB,sugarsB,proteinB,vitaminAB,vitaminCB,vitaminDB,calciumB,
    ironB,potassiumB,foodNameL,caloriesL,saturatedL,transL,
    polyunsaturatedL,monosaturatedL,cholesterolL,sodiumL,carbsL,fiberL,
    sugarsL,proteinL,vitaminAL,vitaminCL,vitaminDL,calciumL,ironL,
    potassiumL,foodNameD,caloriesD,saturatedD,transD,polyunsaturatedD,
    monosaturatedD,cholesterolD,sodiumD,carbsD,fiberD,sugarsD,proteinD,
    vitaminAD,vitaminCD,vitaminDD,calciumD,ironD,potassiumD,foodNameBB,
    caloriesBB,saturatedBB,transBB,polyunsaturatedBB,monosaturatedBB,
    cholesterolBB,sodiumBB,carbsBB,fiberBB,sugarsBB,proteinBB,vitaminABB,
    vitaminCBB,vitaminDBB,calciumBB,ironBB,potassiumBB,foodNameBed,
    caloriesBed,saturatedBed,transBed,polyunsaturatedBed,monosaturatedBed,
    cholesterolBed,sodiumBed,carbsBed,fiberBed,sugarsBed,proteinBed,
    vitaminABed,vitaminCBed,vitaminDBed,calciumBed,ironBed,potassiumBed)
    SELECT user_id,date,foodNameB,caloriesB,saturatedB,
    transB,polyunsaturatedB,monosaturatedB,cholesterolB,sodiumB,carbsB,
    fiberB,sugarsB,proteinB,vitaminAB,vitaminCB,vitaminDB,calciumB,
    ironB,potassiumB,foodNameL,caloriesL,saturatedL,transL,
    polyunsaturatedL,monosaturatedL,cholesterolL,sodiumL,carbsL,fiberL,
    sugarsL,proteinL,vitaminAL,vitaminCL,vitaminDL,calciumL,ironL,
    potassiumL,foodNameD,caloriesD,saturatedD,transD,polyunsaturatedD,
    monosaturatedD,cholesterolD,sodiumD,carbsD,fiberD,sugarsD,proteinD,
    vitaminAD,vitaminCD,vitaminDD,calciumD,ironD,potassiumD,foodNameBB,
    caloriesBB,saturatedBB,transBB,polyunsaturatedBB,monosaturatedBB,
    cholesterolBB,sodiumBB,carbsBB,fiberBB,sugarsBB,proteinBB,vitaminABB,
    vitaminCBB,vitaminDBB,calciumBB,ironBB,potassiumBB,foodNameBed,
    caloriesBed,saturatedBed,transBed,polyunsaturatedBed,monosaturatedBed,
    cholesterolBed,sodiumBed,carbsBed,fiberBed,sugarsBed,proteinBed,
    vitaminABed,vitaminCBed,vitaminDBed,calciumBed,ironBed,potassiumBed
     FROM tmpnutritions order by date, user_id;\
  DROP TEMPORARY TABLE tmpnutritions;`;

const deleteNutrition = `DELETE FROM nutritions WHERE user_id=?;
     ORDER BY id LIMIT 1;
     ${copyNutritionsTable}`;

const deleteAllNutritions =
  `DELETE FROM nutritions WHERE user_id=?;
    ${copyNutritionsTable}`;

const insertNutritions =
  `INSERT INTO nutritions (user_id,date,
    foodNameB,caloriesB,saturatedB,transB,polyunsaturatedB,monosaturatedB,
    cholesterolB,sodiumB,carbsB,fiberB,sugarsB,proteinB,vitaminAB,vitaminCB,
    vitaminDB,calciumB,ironB,potassiumB,foodNameL,caloriesL,saturatedL,
    transL,polyunsaturatedL,monosaturatedL,cholesterolL,sodiumL,carbsL,
    fiberL,sugarsL,proteinL,vitaminAL,vitaminCL,vitaminDL,calciumL,ironL,
    potassiumL,foodNameD,caloriesD,saturatedD,transD,polyunsaturatedD,
    monosaturatedD,cholesterolD,sodiumD,carbsD,fiberD,sugarsD,proteinD,
    vitaminAD,vitaminCD,vitaminDD,calciumD,ironD,potassiumD,foodNameBB,
    caloriesBB,saturatedBB,transBB,polyunsaturatedBB,monosaturatedBB,
    cholesterolBB,sodiumBB,carbsBB,fiberBB,sugarsBB,proteinBB,vitaminABB,
    vitaminCBB,vitaminDBB,calciumBB,ironBB,potassiumBB,foodNameBed,
    caloriesBed,saturatedBed,transBed,polyunsaturatedBed,monosaturatedBed,
    cholesterolBed,sodiumBed,carbsBed,fiberBed,sugarsBed,proteinBed,
    vitaminABed,vitaminCBed,vitaminDBed,calciumBed,ironBed,potassiumBed)
     VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,
     ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,
     ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);`;

const selectNutritions = 'SELECT * FROM nutritions';

const updateNutrition =
  `SET @id=?;SET @user_id=?;SET @date=?;SET @foodNameB=?;
  SET @caloriesB=?;SET@saturatedB=?;SET @transB=?;SET @polyunsaturatedB=?;
  SET @monosaturatedB=?;SET @cholesterolB=?;SET @sodiumB=?;SET @carbsB=?;
  SET @fiberB=?;SET @sugarsB=?;SET @proteinB=?;SET @vitaminAB=?;
  SET @vitaminCB=?;SET @vitaminDB=?;SET @calciumB=?;SET @ironB=?;
  SET @potassiumB=?;SET @foodNameL=?;SET @caloriesL=?;SET @saturatedL=?;
  SET @transL=?;SET @polyunsaturatedL=?;SET @monosaturatedL=?;
  SET @cholesterolL=?;SET @sodiumL=?;SET @carbsL=?;SET @fiberL=?;
  SET @sugarsL=?;SET @proteinL=?;SET @vitaminAL=?;SET @vitaminCL=?;
  SET @vitaminDL=?;SET @calciumL=?;SET @ironL=?;SET @potassiumL=?;
  SET @foodNameD=?;SET @caloriesD=?;SET @saturatedD=?;SET @transD=?;
  SET @polyunsaturatedD=?;SET @monosaturatedD=?;SET @cholesterolD=?;
  SET @sodiumD=?;SET @carbsD=?;SET @fiberD=?;SET @sugarsD=?;SET @proteinD=?;
  SET @vitaminAD=?;SET @vitaminCD=?;SET @vitaminDD=?;SET @calciumD=?;
  SET @ironD=?;SET @potassiumD=?;SET @foodNameBB=?;SET @caloriesBB=?;
  SET @saturatedBB=?;SET @transBB=?;SET @polyunsaturatedBB=?;
  SET @monosaturatedBB=?;SET @cholesterolBB=?;SET @sodiumBB=?;SET @carbsBB=?;
  SET @fiberBB=?;SET @sugarsBB=?;SET @proteinBB=?;SET @vitaminABB=?;
  SET @vitaminCBB=?;SET @vitaminDBB=?;SET @calciumBB=?;SET @ironBB=?;
  SET @potassiumBB=?;SET @foodNameBed=?;SET @caloriesBed=?;
  SET @saturatedBed=?;SET @transBed=?;SET @polyunsaturatedBed=?;
  SET @monosaturatedBed=?;SET @cholesterolBed=?;SET @sodiumBed=?;
  SET @carbsBed=?;SET @fiberBed=?;SET @sugarsBed=?;SET @proteinBed=?;
  SET @vitaminABed=?;SET @vitaminCBed=?;SET @vitaminDBed=?;SET@calciumBed=?;
  SET @ironBed=?;SET @potassiumBed=?; CALL updateNutrition(@id,@user_id,
    @date,@foodNameB,@caloriesB,@saturatedB,@transB,@polyunsaturatedB,
    @monosaturatedB,@cholesterolB,@sodiumB,@carbsB,@fiberB,@sugarsB,
    @proteinB,@vitaminAB,@vitaminCB,@vitaminDB,@calciumB,@ironB,@potassiumB,
    @foodNameL,@caloriesL,@saturatedL,@transL,@polyunsaturatedL,
    @monosaturatedL,@cholesterolL,@sodiumL,@carbsL,@fiberL,@sugarsL,@proteinL,
    @vitaminAL,@vitaminCL,@vitaminDL,@calciumL,@ironL,@potassiumL,@foodNameD,
    @caloriesD,@saturatedD,@transD,@polyunsaturatedD,@monosaturatedD,
    @cholesterolD,@sodiumD,@carbsD,@fiberD,@sugarsD,@proteinD,@vitaminAD,
    @vitaminCD,@vitaminDD,@calciumD,@ironD,@potassiumD,@foodNameBB,
    @caloriesBB,@saturatedBB,@transBB,@polyunsaturatedBB,@monosaturatedBB,
    @cholesterolBB,@sodiumBB,@carbsBB,@fiberBB,@sugarsBB,@proteinBB,
    @vitaminABB,@vitaminCBB,@vitaminDBB,@calciumBB,@ironBB,@potassiumBB,
    @foodNameBed,@caloriesBed,@saturatedBed,@transBed,@polyunsaturatedBed,
    @monosaturatedBed,@cholesterolBed,@sodiumBed,@carbsBed,@fiberBed,
    @sugarsBed,@proteinBed,@vitaminABed,@vitaminCBed,@vitaminDBed,
    @calciumBed,@ironBed,@potassiumBed);`;

module.exports = {
  copyNutritionsTable,
  deleteAllNutritions,
  deleteNutrition,
  insertNutritions,
  selectNutritions,
  updateNutrition,
}