const copyMoviesTable =
    `CREATE TEMPORARY TABLE tmpmovies(
        user_id int not null,
        name text not null,
        featureMedia text not null,
        numMovie int not null,
        name1 text not null,
        rated1 text not null,
        length1 int not null,
        yearR1 int not null,
        media1 text not null,
        name2 text not null,
        rated2 text not null,
        length2 int not null,
        yearR2 int not null,
        media2 text not null,
        name3 text not null,
        rated3 text not null,
        length3 int not null,
        yearR3 int not null,
        media3 text not null,
        name4 text not null,
        rated4 text not null,
        length4 int not null,
        yearR4 int not null,
        media4 text not null,
        name5 text not null,
        rated5 text not null,
        length5 int not null,
        yearR5 int not null,
        media5 text not null,
        name6 text not null,
        rated6 text not null,
        length6 int not null,
        yearR6 int not null,
        media6 text not null,
        name7 text not null,
        rated7 text not null,
        length7 int not null,
        yearR7 int not null,
        media7 text not null,
        name8 text not null,
        rated8 text not null,
        length8 int not null,
        yearR8 int not null,
        media8 text not null,
        name9 text not null,
        rated9 text not null,
        length9 int not null,
        yearR9 int not null,
        media9 text not null,
        name10 text not null,
        rated10 text not null,
        length10 int not null,
        yearR10 int not null,
        media10 text not null,
        name11 text not null,
        rated11 text not null,
        length11 int not null,
        yearR11 int not null,
        media11 text not null,
        name12 text not null,
        rated12 text not null,
        length12 int not null,
        yearR12 int not null,
        media12 text not null,
        io tinyint(1) not null,
        who text not null,
        lost tinyint(1) not null);
      INSERT INTO tmpmovies(user_id,name,featureMedia,numMovie,
        name1,rated1,length1,yearR1,media1,name2,rated2,length2,yearR2,
        media2,name3,rated3,length3,yearR3,media3,name4,rated4,length4,
        yearR4,media4,name5,rated5,length5,yearR5,media5,name6,rated6,
        length6,yearR6,media6,name7,rated7,length7,yearR7,media7,name8,
        rated8,length8,yearR8,media8,name9,rated9,length9,yearR9,media9,
        name10,rated10,length10,yearR10,media10,name11,rated11,length11,
        yearR11,media11,name12,rated12,length12,yearR12,media12,io,who,
        lost)
        SELECT user_id,name,featureMedia,numMovie,
        name1,rated1,length1,yearR1,media1,name2,rated2,length2,yearR2,
        media2,name3,rated3,length3,yearR3,media3,name4,rated4,length4,
        yearR4,media4,name5,rated5,length5,yearR5,media5,name6,rated6,
        length6,yearR6,media6,name7,rated7,length7,yearR7,media7,name8,
        rated8,length8,yearR8,media8,name9,rated9,length9,yearR9,media9,
        name10,rated10,length10,yearR10,media10,name11,rated11,length11,
        yearR11,media11,name12,rated12,length12,yearR12,media12,io,who,
        lost FROM movies;
      DROP TABLE movies;
    CREATE TABLE movies(
        id int not null auto_increment,
        user_id int not null,
        name text not null,
        featureMedia text not null,
        numMovie int not null,
        name1 text not null,
        rated1 text not null,
        length1 int not null,
        yearR1 int not null,
        media1 text not null,
        name2 text not null,
        rated2 text not null,
        length2 int not null,
        yearR2 int not null,
        media2 text not null,
        name3 text not null,
        rated3 text not null,
        length3 int not null,
        yearR3 int not null,
        media3 text not null,
        name4 text not null,
        rated4 text not null,
        length4 int not null,
        yearR4 int not null,
        media4 text not null,
        name5 text not null,
        rated5 text not null,
        length5 int not null,
        yearR5 int not null,
        media5 text not null,
        name6 text not null,
        rated6 text not null,
        length6 int not null,
        yearR6 int not null,
        media6 text not null,
        name7 text not null,
        rated7 text not null,
        length7 int not null,
        yearR7 int not null,
        media7 text not null,
        name8 text not null,
        rated8 text not null,
        length8 int not null,
        yearR8 int not null,
        media8 text not null,
        name9 text not null,
        rated9 text not null,
        length9 int not null,
        yearR9 int not null,
        media9 text not null,
        name10 text not null,
        rated10 text not null,
        length10 int not null,
        yearR10 int not null,
        media10 text not null,
        name11 text not null,
        rated11 text not null,
        length11 int not null,
        yearR11 int not null,
        media11 text not null,
        name12 text not null,
        rated12 text not null,
        length12 int not null,
        yearR12 int not null,
        media12 text not null,
        io tinyint(1) not null,
        who text not null,
        primary key (id));
    INSERT INTO movies(user_id,name,featureMedia,numMovie,
        name1,rated1,length1,yearR1,media1,name2,rated2,length2,yearR2,
        media2,name3,rated3,length3,yearR3,media3,name4,rated4,length4,
        yearR4,media4,name5,rated5,length5,yearR5,media5,name6,rated6,
        length6,yearR6,media6,name7,rated7,length7,yearR7,media7,name8,
        rated8,length8,yearR8,media8,name9,rated9,length9,yearR9,media9,
        name10,rated10,length10,yearR10,media10,name11,rated11,length11,
        yearR11,media11,name12,rated12,length12,yearR12,media12,io,who,
        lost)
        SELECT user_id,name,featureMedia,numMovie,
        name1,rated1,length1,yearR1,media1,name2,rated2,length2,yearR2,
        media2,name3,rated3,length3,yearR3,media3,name4,rated4,length4,
        yearR4,media4,name5,rated5,length5,yearR5,media5,name6,rated6,
        length6,yearR6,media6,name7,rated7,length7,yearR7,media7,name8,
        rated8,length8,yearR8,media8,name9,rated9,length9,yearR9,media9,
        name10,rated10,length10,yearR10,media10,name11,rated11,length11,
        yearR11,media11,name12,rated12,length12,yearR12,media12,io,who,
        lost FROM tmpmovies order by name, user_id;
    DROP TEMPORARY TABLE tmpmovies;`;

const createMoviesTbl =
    `CREATE TABLE IF NOT EXISTS movies(
        id int not null auto_increment,
        user_id int not null,
        name text not null,
        featureMedia text not null,
        numMovie int not null,
        name1 text not null,
        rated1 text not null,
        length1 int not null,
        yearR1 int not null,
        media1 text not null,
        name2 text not null,
        rated2 text not null,
        length2 int not null,
        yearR2 int not null,
        media2 text not null,
        name3 text not null,
        rated3 text not null,
        length3 int not null,
        yearR3 int not null,
        media3 text not null,
        name4 text not null,
        rated4 text not null,
        length4 int not null,
        yearR4 int not null,
        media4 text not null,
        name5 text not null,
        rated5 text not null,
        length5 int not null,
        yearR5 int not null,
        media5 text not null,
        name6 text not null,
        rated6 text not null,
        length6 int not null,
        yearR6 int not null,
        media6 text not null,
        name7 text not null,
        rated7 text not null,
        length7 int not null,
        yearR7 int not null,
        media7 text not null,
        name8 text not null,
        rated8 text not null,
        length8 int not null,
        yearR8 int not null,
        media8 text not null,
        name9 text not null,
        rated9 text not null,
        length9 int not null,
        yearR9 int not null,
        media9 text not null,
        name10 text not null,
        rated10 text not null,
        length10 int not null,
        yearR10 int not null,
        media10 text not null,
        name11 text not null,
        rated11 text not null,
        length11 int not null,
        yearR11 int not null,
        media11 text not null,
        name12 text not null,
        rated12 text not null,
        length12 int not null,
        yearR12 int not null,
        media12 text not null,
        io tinyint(1) not null,
        who text not null,
        lost tinyint(1) not null,
        primary key (id));`;

const deleteAllMovies =
    `DELETE FROM movies WHERE user_id=?;
      ${copyMoviesTable}`;

const deleteMovie =
    `DELETE FROM movies WHERE user_id=?;
     ORDER BY id LIMIT 1;
     ${copyMoviesTable}`;

const insertMovie =
    `INSERT INTO movies(user_id,name,featureMedia,numMovie,
        name1,rated1,length1,yearR1,media1,name2,rated2,length2,yearR2,
        media2,name3,rated3,length3,yearR3,media3,name4,rated4,length4,
        yearR4,media4,name5,rated5,length5,yearR5,media5,name6,rated6,
        length6,yearR6,media6,name7,rated7,length7,yearR7,media7,name8,
        rated8,length8,yearR8,media8,name9,rated9,length9,yearR9,media9,
        name10,rated10,length10,yearR10,media10,name11,rated11,length11,
        yearR11,media11,name12,rated12,length12,yearR12,media12,io,who,
        lost) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,
        ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,
        ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`;

const selectMovies = `select * from movies`;

const updateMovie =
    `SET @id=?;SET @user_id=?;SET @name; SET @featureMedia; SET @numMovie;
        SET @name1; SET @rated1; SET @length1; SET @yearR1; SET @media1;
        SET @name2; SET @rated2; SET @length2; SET @yearR2; SET @media2;
        SET @name3; SET @rated3; SET @length3; SET @yearR3; SET @media3;
        SET @name4; SET @rated4; SET @length4; SET @yearR4; SET @media4;
        SET @name5; SET @rated5; SET @length5; SET @yearR5; SET @media5;
        SET @name6; SET @rated6; SET @length6; SET @yearR6; SET @media6;
        SET @name7; SET @rated7; SET @length7; SET @yearR7; SET @media7;
        SET @name8; SET @rated8; SET @length8; SET @yearR8; SET @media8;
        SET @name9; SET @rated9; SET @length9; SET @yearR9; SET @media9;
        SET @name10; SET @rated10; SET @length10; SET @yearR10;
        SET @media10; SET @name11; SET @rated11; SET @length11;
        SET @yearR11; SET @media11; SET @name12; SET @rated12;
        SET @length12; SET @yearR12; SET @media12; SET @io; SET @who;
        SET @lost;
     CALL updateMovie(@id,@user_id,@name,@featureMedia,@numMovie,
        name1,@rated1,@length1,@yearR1,@media1,@name2,@rated2,@length2,@yearR2,
        media2,@name3,@rated3,@length3,@yearR3,@media3,@name4,@rated4,@length4,
        yearR4,@media4,@name5,@rated5,@length5,@yearR5,@media5,@name6,@rated6,
        length6,@yearR6,@media6,@name7,@rated7,@length7,@yearR7,@media7,@name8,
        rated8,@length8,@yearR8,@media8,@name9,@rated9,@length9,@yearR9,@media9,
        name10,@rated10,@length10,@yearR10,@media10,@name11,@rated11,@length11,
        yearR11,@media11,@name12,@rated12,@length12,@yearR12,@media12,@io,@who,
        @lost);`;

module.exports={
    copyMoviesTable,
    createMoviesTbl,
    deleteAllMovies,
    deleteMovie,
    insertMovie,
    selectMovies,
    updateMovie,
}